# Generated by Django 2.1.2 on 2018-11-05 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='place',
            new_name='places',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='username',
        ),
    ]
