# Generated by Django 2.1.2 on 2018-11-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0002_auto_20181105_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mero',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
