# Generated by Django 2.1.2 on 2018-12-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0006_auto_20181212_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='mero',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Merop',
        ),
    ]
