# Generated by Django 2.1.2 on 2019-01-18 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0007_auto_20181212_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mero', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='mero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bron.Merop'),
        ),
    ]
