# Generated by Django 2.1.2 on 2019-01-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0008_auto_20190118_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merop',
            name='name',
        ),
        migrations.AlterField(
            model_name='merop',
            name='mero',
            field=models.CharField(max_length=30),
        ),
    ]
