# Generated by Django 2.1.2 on 2019-01-20 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0012_auto_20190120_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='mero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bron.Merop'),
        ),
    ]
