# Generated by Django 2.1.2 on 2019-01-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0013_auto_20190120_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merop',
            name='id',
        ),
        migrations.AlterField(
            model_name='merop',
            name='mero',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
