# Generated by Django 2.1.2 on 2019-01-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0014_auto_20190120_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merop',
            name='mero',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
