# Generated by Django 2.1.2 on 2019-01-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0015_auto_20190120_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merop',
            name='prikol',
        ),
        migrations.AddField(
            model_name='merop',
            name='date',
            field=models.DateField(default="2001-12-24"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merop',
            name='place',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
