# Generated by Django 2.1.2 on 2019-01-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0016_auto_20190122_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merop',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
