# Generated by Django 2.1.2 on 2019-01-22 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0017_auto_20190122_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merop',
            name='date',
        ),
    ]
