# Generated by Django 2.1.2 on 2019-01-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0018_remove_merop_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merop',
            name='place',
        ),
        migrations.AddField(
            model_name='merop',
            name='prikol',
            field=models.CharField(default=4, max_length=100),
            preserve_default=False,
        ),
    ]
