# Generated by Django 2.1.2 on 2019-01-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0020_auto_20190122_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vstavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
