# Generated by Django 2.1.5 on 2019-02-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0021_vstavka'),
    ]

    operations = [
        migrations.AddField(
            model_name='merop',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
