# Generated by Django 2.1.2 on 2019-02-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bron', '0022_merop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='conf',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='merop',
            name='place',
            field=models.CharField(default='Улица', max_length=30),
        ),
    ]
